version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: safeaccess_db
    restart: always
    environment:
      POSTGRES_DB: parking_securise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/create_database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - safeaccess_network

networks:
  safeaccess_network:
    driver: bridge

volumes:
  postgres_data: